# Generated by Django 4.0.3 on 2022-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_ticker', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('article_url', models.CharField(max_length=255)),
                ('url_image', models.CharField(max_length=255)),
                ('article_description', models.CharField(max_length=10000)),
                ('date_published', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('date', models.DateTimeField()),
                ('company_ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('high', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('low', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('close', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('volume', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('dividends', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_ticker', models.CharField(max_length=255)),
                ('tweet_url', models.CharField(max_length=255)),
                ('tweet_content', models.CharField(max_length=300)),
                ('date_published', models.DateTimeField()),
                ('follower_count', models.IntegerField()),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 'tweets',
                'managed': False,
            },
        ),
    ]
