TICKERS_COMPANIES_NAME = {
    'AAPL': 'apple',
    'MSFT': 'microsoft',
    'AMZN': 'amazon',
    'TSLA': 'tesla',
    'NVDA': 'nvidia',
    'V': 'visa',
    'UNH': 'unitedhealth',
    'WMT': 'walmart',
    'MA': 'mastercard',
    'RHHBF': 'roche',
    'BABA': 'alibaba',
    'PFE': 'pfizer',
    'ASML': 'asml',
    'TM': 'toyota',
    'KOF': 'coca-cola',
    'CSCO': 'cisco',
    'AVGO': 'broadcom',
    'NKE': 'nike',
    'ACN': 'accenture',
    'ADBE': 'adobe',
    'CVX': 'chevron',
    'PEP': 'pepsico',
    'NFLX': 'netflix',
    'ABBV': 'abbvie',
    'ORCL': 'oracle',
    'CMCSA': 'comcast',
    'VZ': 'verizon',
    'INTC': 'intel',
    'DHR': 'danaher',
    'QCOM': 'qualcomm',
    'NVS': 'novartis',
    'SHLX': 'shell',
    'AZN': 'astrazeneca',
    'LIN': 'linde',
    'INTU': 'intuit',
    'PTR': 'petrochina',
    'MDT': 'medtronic',
    'HSBC': 'hsbc',
    'AMGN': 'amgen',
    '2222.SR': 'saudi aramco',
    'GOOG': 'alphabet',
    'BRK-A': 'berkshire hathaway',
    'FB': 'meta',
    'TSM': 'tsmc',
    'TCEHY': 'tencent',
    'JNJ': 'johnson & johnson',
    '005930.KS': 'samsung',
    'JPM': 'jpmorgan chase',
    'PG': 'procter & gamble',
    '600519.SS': 'kweichow moutai',
    'NSRGY': 'nestle',
    'XOM': 'exxon mobil',
    'BAC': 'bank of america',
    'LVMUY': 'lvmh',
    'HD': 'home depot',
    'DIS': 'walt disney',
    'BHP': 'bhp group',
    '1398.HK': 'icbc',
    'LLY': 'eli lilly',
    'NVO': 'novo nordisk',
    'COST': 'costco',
    'TMO': 'thermo fisher scientific',
    'ABT': 'abbott laboratories',
    'RELIANCE.NS': 'reliance industries',
    'OR.PA': "l'oreal",
    'CRM': 'salesforce',
    '3968.HK': 'cm bank',
    'WFC': 'wells fargo',
    'MRK': 'merck',
    '300750.SZ': 'catl',
    'CICHY': 'china construction bank',
    'UPS': 'united parcel service',
    'AMD': 'amd',
    'PRX.AS': 'prosus',
    'MCD': 'mcdonald',
    'TCS.NS': 'tata consultancy services',
    'T': 'at&t',
    'ACGBY': 'agricultural bank of china',
    'UNP': 'union pacific corporation',
    'PM': 'philip morris',
    'TXN': 'texas instruments',
    'MS': 'morgan stanley',
    'RY': 'royal bank of canada',
    'TMUS': 't-mobile us',
    'NEE': 'nextera energy',
    'SCHW': 'charles schwab',
    'LOW': "lowe's companies",
    'BMY': 'bristol-myers squibb',
    'RTX': 'raytheon technologies',
    'HESAF': 'hermes',
    '0941.HK': 'china mobile',
    'SPGI': 's&p global',
    'TD': 'toronto dominion bank',
    'PNGAY': 'ping an insurance',
    'BACHF': 'bank of china',
    'CVS': 'cvs health',
    'AXP': 'american express',
    'RIO': 'rio tinto',
    'TTE': 'totalenergies',
    'MPNGF': 'meituan'}
