FROM ubuntu:20.04

# Add crontab file in the cron directory
ADD crontab /etc/cron.d/news-cron

# Give [execution?] rights on the cron job
RUN chmod 0644 /etc/cron.d/news-cron
#RUN chmod 0744 /etc/cron.d/news-cron

# Add bash scripts called by cron
ADD run_newsapi.sh /root/run_newsapi.sh
ADD run_stockdata.sh /root/run_stockdata.sh

# Give execution rights to scripts
RUN chmod 0744 /root/run_newsapi.sh
RUN chmod 0744 /root/run_stockdata.sh

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

# Python 3
RUN apt-get -y install python3 python3-pip
#RUN apt-get -y install python3-venv
COPY docker_requirements3.txt /root/docker_requirements3.txt
RUN python3 -m pip install -r /root/docker_requirements3.txt

# Python 2
#RUN apt-get -y install python2

# Copy python/json files to root directory
COPY all_articles_bloomberg.py  /root/all_articles_bloomberg.py 
COPY dailystock.py  /root/dailystock.py

COPY companies.py  /root/companies.py
COPY postGres.py /root/postGres.py
COPY keys.py  /root/keys.py
COPY db_keys.py /root/db_keys.py
COPY creds.json /root/creds.json

# TO REMOVE
RUN apt-get -y install vim

# Run the command on container startup
#CMD cron && tail -f /var/log/cron.log
#CMD ["cron", "-f"]
CMD ["cron", "&&", "tail", "-f", "/var/log/cron.log"]
