insert into companies (company_ticker, company_name, sector, exchange, website) values ('AAPL', 'apple', 'Technology', 'JPY', 'https://independent.co.uk/tellus/semper/interdum.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('2222.SR', 'saudi aramco', 'n/a', 'HNL', 'https://upenn.edu/justo/sollicitudin/ut/suscipit/a/feugiat/et.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MSFT', 'microsoft', 'n/a', 'UAH', 'https://mozilla.org/interdum/venenatis.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('GOOG', 'alphabet', 'Consumer Non-Durables', 'BAM', 'http://pagesperso-orange.fr/sagittis/sapien/cum/sociis.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AMZN', 'amazon', 'Health Care', 'PLN', 'https://qq.com/morbi/non.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TSLA', 'tesla', 'Health Care', 'COP', 'https://ucla.edu/mus.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BRK-A', 'berkshire hathaway', 'Public Utilities', 'VND', 'http://delicious.com/proin/leo/odio/porttitor.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NVDA', 'nvidia', 'n/a', 'BRL', 'https://youtu.be/molestie/nibh/in/lectus/pellentesque.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('FB', 'meta', 'Finance', 'PEN', 'http://a8.net/sodales/sed/tincidunt/eu/felis/fusce/posuere.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TSM', 'tsmc', 'Finance', 'PLN', 'http://gravatar.com/amet/cursus/id/turpis/integer.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TCEHY', 'tencent', 'Capital Goods', 'IDR', 'https://utexas.edu/adipiscing/elit/proin/interdum/mauris.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('UNH', 'unitedhealth', 'Basic Industries', 'CNY', 'http://hhs.gov/dui/proin/leo/odio/porttitor.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('V', 'visa', 'Capital Goods', 'BRL', 'http://facebook.com/ligula/pellentesque/ultrices/phasellus/id/sapien/in.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('JNJ', 'johnson & johnson', 'Energy', 'BRL', 'http://sciencedirect.com/nulla/integer/pede.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('005930.KS', 'samsung', 'n/a', 'CNY', 'http://amazonaws.com/et/commodo/vulputate/justo.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('JPM', 'jpmorgan chase', 'n/a', 'PHP', 'http://admin.ch/purus/eu/magna/vulputate/luctus/cum/sociis.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('WMT', 'walmart', 'Consumer Services', 'RUB', 'https://amazon.co.uk/euismod/scelerisque.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PG', 'procter & gamble', 'n/a', 'CNY', 'https://baidu.com/eros/viverra/eget/congue/eget.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('600519.SS', 'kweichow moutai', 'n/a', 'UAH', 'https://microsoft.com/lorem.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NSRGY', 'nestle', 'Technology', 'ETB', 'http://reverbnation.com/sem/sed/sagittis/nam.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('XOM', 'exxon mobil', 'Technology', 'JPY', 'http://google.es/diam/nam/tristique/tortor.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BAC', 'bank of america', 'Consumer Non-Durables', 'RUB', 'http://dion.ne.jp/congue/risus/semper.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('LVMUY', 'lvmh', 'Basic Industries', 'CNY', 'http://ameblo.jp/magnis.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('HD', 'home depot', 'Technology', 'CNY', 'https://over-blog.com/vel/augue/vestibulum/rutrum/rutrum/neque/aenean.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MA', 'mastercard', 'n/a', 'CNY', 'https://tiny.cc/nec.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('RHHBF', 'roche', 'Technology', 'BWP', 'https://shutterfly.com/nullam/sit/amet/turpis.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CVX', 'chevron', 'Energy', 'USD', 'https://tmall.com/nulla/integer/pede.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BABA', 'alibaba', 'n/a', 'CNY', 'http://yelp.com/molestie/lorem/quisque/ut.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('KOF', 'coca-cola', 'n/a', 'USD', 'http://mapy.cz/vel/accumsan/tellus/nisi/eu.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PFE', 'pfizer', 'n/a', 'EUR', 'http://etsy.com/libero/convallis/eget/eleifend.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ABBV', 'abbvie', 'n/a', 'IDR', 'https://cbc.ca/molestie.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('DIS', 'walt disney', 'Finance', 'IDR', 'https://microsoft.com/morbi/quis/tortor/id.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BHP', 'bhp group', 'Finance', 'MNT', 'https://google.cn/mi/sit/amet/lobortis/sapien/sapien.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('1398.HK', 'icbc', 'Health Care', 'CNY', 'https://nifty.com/habitasse.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ASML', 'asml', 'Technology', 'CUP', 'http://netscape.com/orci.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('LLY', 'eli lilly', 'Finance', 'PHP', 'http://blogspot.com/quam/suspendisse/potenti/nullam/porttitor.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TM', 'toyota', 'Consumer Non-Durables', 'CNY', 'https://vkontakte.ru/venenatis/tristique/fusce/congue.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NVO', 'novo nordisk', 'Consumer Services', 'EUR', 'https://alibaba.com/erat/quisque/erat/eros/viverra/eget.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AVGO', 'broadcom', 'Finance', 'HUF', 'http://opera.com/at/velit/vivamus/vel/nulla/eget.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('COST', 'costco', 'Finance', 'EUR', 'https://naver.com/ultrices/posuere/cubilia.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CSCO', 'cisco', 'n/a', 'EUR', 'http://hugedomains.com/congue/vivamus/metus.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('VZ', 'verizon', 'Capital Goods', 'XAF', 'https://twitter.com/duis/bibendum/morbi/non.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PEP', 'pepsico', 'Consumer Non-Durables', 'CNY', 'http://uiuc.edu/eu/mi/nulla/ac.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ADBE', 'adobe', 'Consumer Non-Durables', 'CNY', 'https://dmoz.org/sapien/non/mi.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TMO', 'thermo fisher scientific', 'n/a', 'CNY', 'https://unblog.fr/in/hac.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CMCSA', 'comcast', 'Consumer Services', 'RUB', 'https://noaa.gov/pretium.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ABT', 'abbott laboratories', 'Capital Goods', 'MDL', 'https://google.co.uk/pede/posuere/nonummy/integer.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('RELIANCE.NS', 'reliance industries', 'n/a', 'RSD', 'https://bbb.org/morbi/non/quam/nec/dui.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NKE', 'nike', 'Basic Industries', 'PLN', 'https://techcrunch.com/enim/sit.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ORCL', 'oracle', 'Capital Goods', 'XPF', 'https://ed.gov/et/magnis/dis/parturient/montes/nascetur/ridiculus.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('OR.PA', 'loreal', 'Technology', 'RUB', 'http://msn.com/aliquet/maecenas/leo/odio.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('SHLX', 'shell', 'Consumer Services', 'NGN', 'https://ucoz.com/in/hac/habitasse/platea.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CRM', 'salesforce', 'Technology', 'IDR', 'http://woothemes.com/nam.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ACN', 'accenture', 'Health Care', 'EUR', 'http://abc.net.au/nisl/venenatis/lacinia/aenean/sit/amet/justo.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('3968.HK', 'cm bank', 'Capital Goods', 'UAH', 'https://cocolog-nifty.com/cum/sociis.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('DHR', 'danaher', 'n/a', 'EUR', 'https://yahoo.co.jp/diam/cras/pellentesque/volutpat/dui/maecenas/tristique.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('WFC', 'wells fargo', 'n/a', 'THB', 'https://addtoany.com/sapien/urna/pretium/nisl.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('INTC', 'intel', 'Health Care', 'PHP', 'http://npr.org/orci.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MRK', 'merck', 'Health Care', 'USD', 'http://chicagotribune.com/morbi/quis/tortor/id/nulla/ultrices.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NVS', 'novartis', 'n/a', 'SYP', 'https://noaa.gov/justo/in/hac/habitasse/platea/dictumst/etiam.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('300750.SZ', 'catl', 'Consumer Services', 'IDR', 'http://cocolog-nifty.com/accumsan/felis/ut/at/dolor.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CICHY', 'china construction bank', 'Consumer Non-Durables', 'JPY', 'http://arizona.edu/imperdiet.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('QCOM', 'qualcomm', 'Technology', 'CRC', 'https://fastcompany.com/aliquam/non/mauris/morbi.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AZN', 'astrazeneca', 'Finance', 'PLN', 'https://cbslocal.com/eleifend/pede/libero.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('UPS', 'united parcel service', 'Basic Industries', 'CDF', 'http://mac.com/ac/tellus.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AMD', 'amd', 'Public Utilities', 'RUB', 'https://businesswire.com/convallis/nulla/neque.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PRX.AS', 'prosus', 'Energy', 'EUR', 'http://xing.com/dictumst/maecenas.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MCD', 'mcdonald', 'Consumer Services', 'RUB', 'http://columbia.edu/vestibulum.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TCS.NS', 'tata consultancy services', 'Energy', 'IDR', 'https://quantcast.com/sem/fusce/consequat/nulla/nisl.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('T', 'at&t', 'Technology', 'SEK', 'http://cnet.com/duis.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NFLX', 'netflix', 'Health Care', 'RUB', 'http://newyorker.com/ante/ipsum/primis/in.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('ACGBY', 'agricultural bank of china', 'n/a', 'CNY', 'http://ameblo.jp/feugiat/non/pretium/quis/lectus/suspendisse/potenti.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('UNP', 'union pacific corporation', 'n/a', 'IDR', 'https://soup.io/auctor.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PTR', 'petrochina', 'Technology', 'CNY', 'https://psu.edu/mollis.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PM', 'philip morris', 'Consumer Services', 'CNY', 'https://earthlink.net/id/pretium/iaculis/diam/erat/fermentum.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TXN', 'texas instruments', 'Health Care', 'IDR', 'http://va.gov/ut/massa.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MS', 'morgan stanley', 'n/a', 'JPY', 'http://ucsd.edu/odio.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('RY', 'royal bank of canada', 'Finance', 'SEK', 'https://wikimedia.org/nascetur/ridiculus/mus/etiam/vel/augue/vestibulum.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TMUS', 't-mobile us', 'Finance', 'PLN', 'https://indiegogo.com/donec/posuere/metus.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('NEE', 'nextera energy', 'Capital Goods', 'XAF', 'http://oaic.gov.au/ultrices/posuere/cubilia/curae/nulla/dapibus.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('SCHW', 'charles schwab', 'Consumer Services', 'CNY', 'http://unc.edu/dapibus/at/diam/nam/tristique/tortor/eu.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('LOW', 'lowes companies', 'Finance', 'PHP', 'http://prweb.com/aenean/lectus.jsp');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BMY', 'bristol-myers squibb', 'Public Utilities', 'IDR', 'https://walmart.com/praesent.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('RTX', 'raytheon technologies', 'Technology', 'PLN', 'https://unicef.org/varius/integer/ac/leo/pellentesque/ultrices/mattis.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('HESAF', 'hermes', 'Technology', 'CNY', 'http://alexa.com/nunc/viverra/dapibus.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('LIN', 'linde', 'Health Care', 'EUR', 'https://arizona.edu/rhoncus/mauris.xml');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('0941.HK', 'china mobile', 'n/a', 'CLP', 'http://google.co.jp/fusce/congue/diam/id.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MDT', 'medtronic', 'Finance', 'PLN', 'https://unicef.org/ligula/suspendisse/ornare/consequat/lectus.png');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('SPGI', 's&p global', 'Consumer Services', 'RUB', 'http://studiopress.com/tempus/vivamus/in/felis/eu/sapien.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TD', 'toronto dominion bank', 'Technology', 'CNY', 'https://epa.gov/leo/maecenas.aspx');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('PNGAY', 'ping an insurance', 'n/a', 'IDR', 'http://hatena.ne.jp/pede/ullamcorper/augue/a/suscipit/nulla.html');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('BACHF', 'bank of china', 'Consumer Services', 'VND', 'http://alexa.com/aliquet/ultrices.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('CVS', 'cvs health', 'Capital Goods', 'PHP', 'https://macromedia.com/dictumst/maecenas/ut/massa/quis/augue.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AXP', 'american express', 'Energy', 'EUR', 'http://ezinearticles.com/id/luctus/nec.jpg');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('RIO', 'rio tinto', 'Health Care', 'IDR', 'http://squarespace.com/justo/in/hac.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('HSBC', 'hsbc', 'Health Care', 'THB', 'https://statcounter.com/in/eleifend/quam/a/odio.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('INTU', 'intuit', 'Finance', 'EUR', 'http://jimdo.com/ut/rhoncus/aliquet/pulvinar.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('TTE', 'totalenergies', 'n/a', 'CNY', 'http://joomla.org/neque/libero/convallis/eget/eleifend/luctus/ultricies.json');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('MPNGF', 'meituan', 'Public Utilities', 'MGA', 'https://gizmodo.com/posuere/cubilia/curae.js');
insert into companies (company_ticker, company_name, sector, exchange, website) values ('AMGN', 'amgen', 'Energy', 'IDR', 'https://ning.com/nulla/ultrices/aliquet/maecenas/leo/odio/condimentum.xml');
